OMAIL.WA.exec_no_error('
  CREATE TABLE OMAIL.WA.RES_MIME_TYPES (
    ID          INTEGER NOT NULL,
    MIME_TYPE   VARCHAR(30) NOT NULL,
    DESCRIPTION	VARCHAR(255),
    ICON16     	LONG VARBINARY,
    ICON32     	LONG VARBINARY,

    PRIMARY KEY (ID)
  )'
)
;

OMAIL.WA.exec_no_error('
  CREATE TABLE OMAIL.WA.RES_MIME_EXT (
    EXT_ID    INTEGER,
    MIME_ID   INTEGER,
    EXT_NAME  VARCHAR,

    PRIMARY KEY (EXT_ID)
  )'
)
;

OMAIL.WA.exec_no_error(
 'ALTER TABLE OMAIL.WA.RES_MIME_EXT ADD FOREIGN KEY (MIME_ID) REFERENCES OMAIL.WA.RES_MIME_TYPES(ID)'
)
;