

PHOTO.WA._exec_no_error(
'
CREATE TABLE PHOTO.WA.comments(
  COMMENT_ID  INTEGER NOT NULL,
  RES_ID      INTEGER NOT NULL,
  CREATE_DATE DATETIME NOT NULL,
  USER_ID     INTEGER  NOT NULL,
  TEXT        varchar  NULL,

  PRIMARY KEY(COMMENT_ID))'
)
;

PHOTO.WA._exec_no_error(
'
CREATE TABLE PHOTO.WA.SYS_INFO(
  GALLERY_ID    INTEGER NOT NULL,
  OWNER_ID      INTEGER NOT NULL,
  WAI_NAME      VARCHAR NOT NULL,
  HOME_URL      VARCHAR NOT NULL,
  HOME_PATH     VARCHAR NOT NULL,

  PRIMARY KEY(GALLERY_ID))'
)
;
